version: '3'    

services:
  alura-api:
    image: node:15
    container_name: alura-api
    env_file: .env
    restart: always
    working_dir: /home/node/app
    command: npm start
    ports:
      - 8081:${API_PORT}
    volumes:
      - ./:/home/node/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - 5432:${PG_PORT}